### ISSUE TITLE
inputs

### ISSUE THREAD

**Issue by 1728123chen** [bargavjayaraman/secure_model_aggregation#1]
sorry to trouble you.
I have a question but do not know who can help me.
the error is

How does the data "beta" in the inputs folder come into being and from which part of the code?

Thank you very much!

**Comment by bargavjayaraman** [comment]
The beta is the model parameters that you can save to a file.

For instance, the model_wrapper.py code (https://github.com/bargavj/distributedMachineLearning/blob/master/model_wrapper.py) has commented section of the code which saves the beta into a file. Though this is not a clean way to do, I should clean the code.
