### ISSUE TITLE
the number of gates

### ISSUE THREAD

**Issue by 1728123chen** [bargavjayaraman/secure_model_aggregation#2]
Hi friends! Thank you for your great work .I am having some problems .
What does "the number of gates for MPC" mean? How do you count gates in your codes?Could you give relevant algorithms or learning links?

**Comment by bargavjayaraman** [comment]
We refer to the number of garbled gates in the garbled circuit for the MPC protocol. You can refer to the documentation of the Obliv-C (https://oblivc.org) for more details. We count the number of AND/OR gates in the garbled circuit.
